trigger:
- main
- development

pool:
 name: Home
 
resources:
  repositories:
    - repository: templates
      type: git
      name: Fabric/Pipeline

stages:
  - stage: Build
    jobs:
    - template: BuildLibrary.yml@templates
      parameters:
        packagesToPack: '**/Insights.csproj'

  - stage: Publish Internal
    jobs:
    - template: PublishToArtifacts.yml@templates
      
  - stage: Publish to Nuget
    condition: eq(variables['build.sourceBranch'], 'refs/heads/main')
    jobs:
    - template: PublishToNuget.yml@templates
      
