trigger:
- main

resources:
  repositories:
    - repository: templates
      type: git
      name: Fabric/Pipeline

stages:
  - stage: Build
    jobs:
    - template: BuildLibrary.yml@templates
      parameters:
        packagesToPack: '**/Insights.csproj'

  - stage: Publish
    jobs:
    - job: PublishToArtifacts
      steps:
      - task: NuGetCommand@2
        displayName: 'Publish to nuget.org'
        inputs:
          command: 'push'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'Nuget.org'
    
